# Generated by Django 4.0 on 2022-01-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0002_workgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkGallery',
        ),
    ]
