# Generated by Django 4.0 on 2022-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_delete_workgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_ar',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_ar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
